Baichuan-13B-Chat:
  auto_merge_lora_single: true
  auto_quantize: false
  enable: false
  max_batch_size: 1
  model_config:
    do_lower_case: null
    lora: {}
    model_name_or_path: /data/nlp/pre_models/torch/baichuan/Baichuan-13B-Chat
    model_type: baichuan
    use_fast_tokenizer: false
  work_mode: deepspeed
  workers:
  - device_id:
    - 0
baichuan-13b-chat-int4:
  auto_merge_lora_single: true
  auto_quantize: false
  enable: false
  max_batch_size: 1
  model_config:
    do_lower_case: null
    lora: {}
    model_name_or_path: /data/nlp/pre_models/torch/baichuan2/baichuan-13b-chat-int4
    model_type: baichuan
    use_fast_tokenizer: false
  work_mode: deepspeed
  workers:
  - device_id:
    - 0
