bloom-1b7:
  auto_merge_lora_single: true
  auto_quantize: false
  enable: false
  max_batch_size: 1
  model_config:
    do_lower_case: null
    lora: {}
    model_name_or_path: /data/nlp/pre_models/torch/bloom/bloom-1b7
    model_type: bloom
    use_fast_tokenizer: false
  work_mode: deepspeed
  workers:
  - device_id:
    - 0
bloom-560m:
  auto_merge_lora_single: true
  auto_quantize: false
  enable: false
  max_batch_size: 1
  model_config:
    do_lower_case: null
    lora: {}
    model_name_or_path: /data/nlp/pre_models/torch/bloom/bloom-560m
    model_type: bloom
    use_fast_tokenizer: false
  work_mode: deepspeed
  workers:
  - device_id:
    - 0
