opt-350m:
  auto_merge_lora_single: true
  auto_quantize: false
  enable: false
  max_batch_size: 1
  model_config:
    do_lower_case: null
    lora: {}
    model_name_or_path: /data/nlp/pre_models/torch/opt/opt-350m
    model_type: opt
    use_fast_tokenizer: false
  work_mode: deepspeed
  workers:
  - device_id:
    - 0
