Qwen-7B:
  auto_merge_lora_single: true
  auto_quantize: false
  enable: false
  max_batch_size: 1
  model_config:
    do_lower_case: null
    lora: {}
    model_name_or_path: /data/nlp/pre_models/torch/qwen/Qwen-7B
    model_type: qwen
    use_fast_tokenizer: false
  work_mode: deepspeed
  workers:
  - device_id:
    - 0
Qwen-7B-Chat:
  auto_merge_lora_single: true
  auto_quantize: false
  enable: false
  max_batch_size: 1
  model_config:
    do_lower_case: null
    lora: {}
    model_name_or_path: /data/nlp/pre_models/torch/qwen/Qwen-7B-Chat
    model_type: qwen
    use_fast_tokenizer: false
  work_mode: deepspeed
  workers:
  - device_id:
    - 0
qwen-7b-chat-int4:
  auto_merge_lora_single: true
  auto_quantize: false
  enable: false
  max_batch_size: 1
  model_config:
    do_lower_case: null
    lora: {}
    model_name_or_path: /data/nlp/pre_models/torch/qwen/qwen-7b-chat-int4
    model_type: qwen
    use_fast_tokenizer: false
  work_mode: deepspeed
  workers:
  - device_id:
    - 0
