rwkv-4-raven-3b-v12-Eng49%-Chn49%-Jpn1%-Other1%:
  auto_merge_lora_single: true
  auto_quantize: false
  enable: false
  max_batch_size: 1
  model_config:
    do_lower_case: null
    lora: {}
    model_name_or_path: /data/nlp/pre_models/torch/rwkv_gf/rwkv-4-raven-3b-v12
    model_type: rwkv
    use_fast_tokenizer: true
  work_mode: deepspeed
  workers:
  - device_id:
    - 0
